name: Update YouTube IPTV

on:
  schedule:
    - cron: '0 */3 * * *' # Berjalan setiap 3 jam
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git Configuration
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Pull latest changes safely
        run: |
          git fetch origin main
          git pull origin main --rebase -Xours || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade yt-dlp

      - name: Run script
        run: python generate_youtube_m3u.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update: Refresh YouTube streams (every 3 hours)"
          file_pattern: ich-iptv.m3u youtube_source.txt cookies.txt
